initialSize: 1000
updateSize: 1000
numUpdates: 2

ontology: specific.ont

debug: false
transform: false

regions: {
   16-23: {
      pyroLength: 95
      alpha: 0.995
      beta: 0.99
   }

   23-5: {
      pyroLength: 93
      alpha: 0.995
      beta: 0.99
   }
}

metrics: {
   cluster: com.drin.java.metrics.ClusterAverageMetric
   isolate: com.drin.java.metrics.IsolateAverageMetric
   itsregion: com.drin.java.metrics.ITSRegionMedianMetric
   pyroprint: com.drin.java.metrics.PyroprintUnstablePearsonMetric
}
