FILES=Main.java


kNearest.class : kNearest.java
	javac -deprecation kNearest/kNearest.java

kNearest.java :


clean:
	rm kNearest/*.class

run:
	java kNearest/kNearest data/Jen-AliceCombData-P1-P8.csv 16
